apiVersion: v1                  # version
kind: Service                    # kind name
metadata:                         # data about kind
  name: myapp-service
spec:                     
  type: NodePort                  # which type of service it is
  ports:
    - port: 80                  # port of service itself
      targetPort: 80            # port of pod
      nodePort: 30004           # port of node
  selector:
    app: myapp                # assisgning labels to link service to our pods


---

apiVersion: v1                  # version
kind: Service                    # kind name
metadata:                         # data about kind
  name: myapp-service
spec:                     
  type: ClusterIP                 # which type of service it is
  ports:
    - port: 80                  # port of service itself
      targetPort: 80            # port of pod
                 
  selector:
    app: myapp                # assisgning labels to link service to our pods

--- 

apiVersion: v1                  # version
kind: Service                    # kind name
metadata:                         # data about kind
  name: myapp-service
spec:                     
  type: LoadBalancer                 # which type of service it is
  ports:
    - port: 80                  # port of service itself
      targetPort: 80            # port of pod
      nodePort: 30004           # port of node
  selector:
    app: myapp                # assisgning labels to link service to our pods
